# Generated by Django 5.1.2 on 2024-11-01 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('banco', models.CharField(max_length=50)),
                ('agencia', models.CharField(max_length=10)),
                ('conta', models.CharField(max_length=20)),
                ('pix', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
