# Generated by Django 5.1.2 on 2024-11-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dadosusuario_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('cpf_vendedor', models.CharField(max_length=14)),
                ('nome_vendedor', models.CharField(max_length=100)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_boletos', models.IntegerField()),
                ('valor_por_boleto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao_venda', models.TextField()),
                ('forma_pagamento', models.CharField(max_length=10)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
