# Generated by Django 5.1.2 on 2024-11-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cadastrovendas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrovendas',
            name='cpf_vendedor',
        ),
        migrations.AlterField(
            model_name='cadastrovendas',
            name='nome_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dadosusuario'),
        ),
    ]
