# Generated by Django 5.1.2 on 2024-11-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_cadastrovendas_cpf_vendedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrovendas',
            old_name='nome_vendedor',
            new_name='vendedor',
        ),
    ]
